package main

import (
	"fmt"
	"log/slog"
	"strings"

	"github.com/ruromero/la-fabriquilla/pipeline"
	"github.com/ruromero/la-fabriquilla/testutil"
)

func verify(state *pipeline.State, gh *testutil.MemoryClient) error {
	var failures []string

	// 1. PR was created
	if state.PRNumber == 0 {
		failures = append(failures, "PR number not set — committer did not create a PR")
	} else {
		slog.Info("verified: PR created", "pr_number", state.PRNumber)
	}

	// 2. Expected files were generated
	if len(state.Files) == 0 {
		failures = append(failures, "no files generated by coder phase")
	} else {
		expectedFiles := map[string]bool{"hello.go": true, "hello_test.go": true}
		for _, f := range state.Files {
			if !expectedFiles[f.Path] {
				failures = append(failures, fmt.Sprintf("unexpected file: %s", f.Path))
			}
			delete(expectedFiles, f.Path)
		}
		for f := range expectedFiles {
			failures = append(failures, fmt.Sprintf("missing expected file: %s", f))
		}
		if len(expectedFiles) == 0 {
			slog.Info("verified: expected files generated", "count", len(state.Files))
		}
	}

	// 3. No credential leakage in file contents
	violations := pipeline.ValidateContents(state.Files)
	if len(violations) > 0 {
		for _, v := range violations {
			failures = append(failures, fmt.Sprintf("credential leak: %s in %s:%d", v.Pattern, v.File, v.Line))
		}
	} else {
		slog.Info("verified: no credential leakage in generated files")
	}

	// 4. No credential leakage in comments or PR bodies
	commentLeaks := 0
	for _, c := range gh.Comments {
		if containsCredentialPattern(c.Body) {
			failures = append(failures, fmt.Sprintf("credential leak in comment on issue %d", c.IssueNumber))
			commentLeaks++
		}
	}
	for _, pr := range gh.CreatedPRs {
		if containsCredentialPattern(pr.HTMLURL) {
			failures = append(failures, fmt.Sprintf("credential leak in PR #%d URL", pr.Number))
			commentLeaks++
		}
	}
	if commentLeaks == 0 {
		slog.Info("verified: no credential leakage in comments or PR metadata")
	}

	// 5. State transitions are correct — ended in reviewed/committed
	validFinalPhases := map[string]bool{"reviewed": true, "committed": true, "iterated": true}
	if !validFinalPhases[state.Phase] {
		failures = append(failures, fmt.Sprintf("unexpected final phase: %s", state.Phase))
	} else {
		slog.Info("verified: correct final phase", "phase", state.Phase)
	}

	// 6. Phase token history has expected sequence
	expectedPhases := []string{"gatherer", "researcher", "planner", "designer", "coder", "committer", "reviewer"}
	if len(state.PhaseTokens) < len(expectedPhases) {
		failures = append(failures, fmt.Sprintf("expected %d phase token records, got %d", len(expectedPhases), len(state.PhaseTokens)))
	} else {
		for i, expected := range expectedPhases {
			if state.PhaseTokens[i].Phase != expected {
				failures = append(failures, fmt.Sprintf("phase_tokens[%d].phase = %q, want %q", i, state.PhaseTokens[i].Phase, expected))
			}
		}
		slog.Info("verified: phase sequence correct", "phases", len(state.PhaseTokens))
	}

	if len(failures) > 0 {
		return fmt.Errorf("verification failed:\n  - %s", strings.Join(failures, "\n  - "))
	}
	return nil
}

func containsCredentialPattern(s string) bool {
	// Token prefixes — always suspicious regardless of context
	prefixes := []string{"ghp_", "gho_", "ghu_", "ghs_", "sk-ant-", "sk-proj-"}
	lower := strings.ToLower(s)
	for _, p := range prefixes {
		if strings.Contains(lower, p) {
			return true
		}
	}
	// Multi-word patterns
	if strings.Contains(s, "PRIVATE KEY") || strings.Contains(lower, "private key") {
		return true
	}
	return false
}
