package main

import (
	"fmt"
	"log/slog"
	"strings"

	"github.com/ruromero/la-fabriquilla/pipeline"
	"github.com/ruromero/la-fabriquilla/testutil"
)

func verify(state *pipeline.State, gh *testutil.MemoryClient) error {
	var failures []string

	// 1. PR was created
	if state.PRNumber == 0 {
		failures = append(failures, "PR number not set — committer did not create a PR")
	} else {
		slog.Info("verified: PR created", "pr_number", state.PRNumber)
	}

	// 2. Files were generated
	if len(state.Files) == 0 {
		failures = append(failures, "no files generated by coder phase")
	} else {
		slog.Info("verified: files generated", "count", len(state.Files))
	}

	// 3. No credential leakage in file contents
	violations := pipeline.ValidateContents(state.Files)
	if len(violations) > 0 {
		for _, v := range violations {
			failures = append(failures, fmt.Sprintf("credential leak: %s in %s:%d", v.Pattern, v.File, v.Line))
		}
	} else {
		slog.Info("verified: no credential leakage in generated files")
	}

	// 4. No credential leakage in PR body (check comments posted to GitHub)
	for _, c := range gh.Comments {
		if containsCredentialPattern(c.Body) {
			failures = append(failures, fmt.Sprintf("credential leak in comment on issue %d", c.IssueNumber))
		}
	}
	slog.Info("verified: no credential leakage in comments")

	// 5. State transitions are correct — ended in reviewed/committed
	validFinalPhases := map[string]bool{"reviewed": true, "committed": true, "iterated": true}
	if !validFinalPhases[state.Phase] {
		failures = append(failures, fmt.Sprintf("unexpected final phase: %s", state.Phase))
	} else {
		slog.Info("verified: correct final phase", "phase", state.Phase)
	}

	// 6. Phase token history has expected sequence
	expectedPhases := []string{"gatherer", "researcher", "planner", "designer", "coder", "committer", "reviewer"}
	if len(state.PhaseTokens) < len(expectedPhases) {
		failures = append(failures, fmt.Sprintf("expected %d phase token records, got %d", len(expectedPhases), len(state.PhaseTokens)))
	} else {
		for i, expected := range expectedPhases {
			if state.PhaseTokens[i].Phase != expected {
				failures = append(failures, fmt.Sprintf("phase_tokens[%d].phase = %q, want %q", i, state.PhaseTokens[i].Phase, expected))
			}
		}
		slog.Info("verified: phase sequence correct", "phases", len(state.PhaseTokens))
	}

	if len(failures) > 0 {
		return fmt.Errorf("verification failed:\n  - %s", strings.Join(failures, "\n  - "))
	}
	return nil
}

func containsCredentialPattern(s string) bool {
	patterns := []string{
		"ghp_", "gho_", "ghu_", "ghs_",
		"PRIVATE KEY",
		"sk-",
		"password",
		"secret",
	}
	lower := strings.ToLower(s)
	for _, p := range patterns {
		if strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	return false
}
