// tests/smoke_test.go
package tests

import (
	"context"
	"testing"
	"time"

	"github.com/ruromero/la-fabriquilla/github"
	"github.com/ruromero/la-fabriquilla/pipeline"
	"github.com/ruromero/la-fabriquilla/testutil"
)

func TestSmokePipeline(t *testing.T) {
	stateDir := t.TempDir()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	gh := testutil.NewMemoryClient("smoke-owner", "smoke-repo",
		testutil.WithIssue(github.Issue{
			Number: 1,
			Title:  "Add greeting function",
			Body:   "Add a Greet(name string) function that returns \"Hello, <name>!\"",
			Labels: []github.Label{{Name: "fabriquilla:ready"}},
		}),
	)

	runner := testutil.NewCannedPhaseRunner()
	store := pipeline.NewFileStateStore(stateDir)
	key := pipeline.StateKey("smoke-owner", "smoke-repo", 1)

	state := &pipeline.State{
		RepoOwner:   "smoke-owner",
		RepoName:    "smoke-repo",
		IssueNumber: 1,
		Phase:       "init",
		IssueTitle:  "Add greeting function",
		IssueBody:   "Add a Greet(name string) function",
		StartedAt:   time.Now(),
	}
	if err := store.Save(ctx, key, state); err != nil {
		t.Fatal(err)
	}
	statePath := store.StatePath(key)

	phases := []string{"gatherer", "researcher", "planner", "designer", "coder", "committer", "reviewer"}
	for _, phase := range phases {
		if err := runner.Run(ctx, phase, statePath); err != nil {
			t.Fatalf("phase %s failed: %v", phase, err)
		}
	}

	state, err := store.Load(ctx, key)
	if err != nil {
		t.Fatal(err)
	}

	// Verify PR created
	if state.PRNumber == 0 {
		t.Error("PR number not set after committer")
	}

	// Verify files generated
	if len(state.Files) == 0 {
		t.Error("no files generated by coder")
	}

	// Verify no credential leakage
	violations := pipeline.ValidateContents(state.Files)
	if len(violations) > 0 {
		for _, v := range violations {
			t.Errorf("credential leak: %s in %s:%d", v.Pattern, v.File, v.Line)
		}
	}

	// Verify state transitions
	validFinalPhases := map[string]bool{"reviewed": true, "committed": true, "iterated": true}
	if !validFinalPhases[state.Phase] {
		t.Errorf("unexpected final phase: %s", state.Phase)
	}

	// Verify phase token sequence
	expectedPhases := []string{"gatherer", "researcher", "planner", "designer", "coder", "committer", "reviewer"}
	if len(state.PhaseTokens) != len(expectedPhases) {
		t.Fatalf("expected %d phase token records, got %d", len(expectedPhases), len(state.PhaseTokens))
	}
	for i, expected := range expectedPhases {
		if state.PhaseTokens[i].Phase != expected {
			t.Errorf("phase_tokens[%d].phase = %q, want %q", i, state.PhaseTokens[i].Phase, expected)
		}
	}

	// Verify label transitions on the in-memory GitHub
	_ = gh.AddLabel(ctx, 1, "fabriquilla:in-progress")
	_ = gh.RemoveLabel(ctx, 1, "fabriquilla:ready")
	labels := gh.Labels(1)
	hasInProgress := false
	for _, l := range labels {
		if l == "fabriquilla:in-progress" {
			hasInProgress = true
		}
		if l == "fabriquilla:ready" {
			t.Error("issue should not still have fabriquilla:ready label")
		}
	}
	if !hasInProgress {
		t.Error("issue should have fabriquilla:in-progress label")
	}

	// Verify completes within timeout (implicit — context would cancel)
	t.Logf("smoke test passed: PR #%d, %d files, %d phases completed in %v",
		state.PRNumber, len(state.Files), len(state.PhaseTokens), time.Since(state.StartedAt))
}

func TestSmokePipelineReviewIteration(t *testing.T) {
	stateDir := t.TempDir()
	ctx := context.Background()

	runner := testutil.NewCannedPhaseRunner()
	store := pipeline.NewFileStateStore(stateDir)
	key := pipeline.StateKey("smoke-owner", "smoke-repo", 2)

	state := &pipeline.State{
		RepoOwner:   "smoke-owner",
		RepoName:    "smoke-repo",
		IssueNumber: 2,
		Phase:       "init",
		IssueTitle:  "Test iteration",
		IssueBody:   "Test",
		StartedAt:   time.Now(),
	}
	if err := store.Save(ctx, key, state); err != nil {
		t.Fatal(err)
	}
	statePath := store.StatePath(key)

	// Run through to committed
	for _, phase := range []string{"gatherer", "researcher", "planner", "designer", "coder", "committer"} {
		if err := runner.Run(ctx, phase, statePath); err != nil {
			t.Fatalf("%s: %v", phase, err)
		}
	}

	// Simulate review-iterate loop
	if err := runner.Run(ctx, "reviewer", statePath); err != nil {
		t.Fatalf("reviewer: %v", err)
	}
	state, _ = store.Load(ctx, key)
	if state.Phase != "reviewed" {
		t.Errorf("phase = %q after reviewer, want reviewed", state.Phase)
	}

	// Iterator advances iteration counter
	if err := runner.Run(ctx, "iterator", statePath); err != nil {
		t.Fatalf("iterator: %v", err)
	}
	state, _ = store.Load(ctx, key)
	if state.Iteration != 1 {
		t.Errorf("iteration = %d, want 1", state.Iteration)
	}
}
